
# cargo-vet config file

[[exemptions.ansi_term]]
version = "0.12.1"
criteria = "safe-to-deploy"

[[exemptions.atty]]
version = "0.2.14"
criteria = "safe-to-deploy"

[[exemptions.bitflags]]
version = "1.3.2"
criteria = "safe-to-deploy"

[[exemptions.cfg-if]]
version = "1.0.0"
criteria = "safe-to-deploy"

[[exemptions.clap]]
version = "2.34.0"
criteria = "safe-to-deploy"

[[exemptions.disjoint-sets]]
version = "0.4.2"
criteria = "safe-to-deploy"

[[exemptions.getrandom]]
version = "0.2.7"
criteria = "safe-to-deploy"

[[exemptions.heck]]
version = "0.3.3"
criteria = "safe-to-deploy"

[[exemptions.hermit-abi]]
version = "0.1.19"
criteria = "safe-to-deploy"

[[exemptions.itoa]]
version = "1.0.3"
criteria = "safe-to-deploy"

[[exemptions.lazy_static]]
version = "1.4.0"
criteria = "safe-to-deploy"

[[exemptions.libc]]
version = "0.2.132"
criteria = "safe-to-deploy"

[[exemptions.num_threads]]
version = "0.1.6"
criteria = "safe-to-deploy"

[[exemptions.ppv-lite86]]
version = "0.2.16"
criteria = "safe-to-deploy"

[[exemptions.proc-macro-error]]
version = "1.0.4"
criteria = "safe-to-deploy"

[[exemptions.proc-macro-error-attr]]
version = "1.0.4"
criteria = "safe-to-deploy"

[[exemptions.proc-macro2]]
version = "1.0.43"
criteria = "safe-to-deploy"

[[exemptions.quote]]
version = "1.0.21"
criteria = "safe-to-deploy"

[[exemptions.rand]]
version = "0.8.5"
criteria = "safe-to-deploy"

[[exemptions.rand_chacha]]
version = "0.3.1"
criteria = "safe-to-deploy"

[[exemptions.rand_core]]
version = "0.6.4"
criteria = "safe-to-deploy"

[[exemptions.ryu]]
version = "1.0.11"
criteria = "safe-to-deploy"

[[exemptions.serde]]
version = "1.0.144"
criteria = "safe-to-deploy"

[[exemptions.serde_derive]]
version = "1.0.144"
criteria = "safe-to-deploy"

[[exemptions.serde_json]]
version = "1.0.85"
criteria = "safe-to-deploy"

[[exemptions.strsim]]
version = "0.8.0"
criteria = "safe-to-deploy"

[[exemptions.structopt]]
version = "0.3.26"
criteria = "safe-to-deploy"

[[exemptions.structopt-derive]]
version = "0.4.18"
criteria = "safe-to-deploy"

[[exemptions.syn]]
version = "1.0.99"
criteria = "safe-to-deploy"

[[exemptions.textwrap]]
version = "0.11.0"
criteria = "safe-to-deploy"

[[exemptions.time]]
version = "0.3.14"
criteria = "safe-to-deploy"

[[exemptions.time-macros]]
version = "0.2.4"
criteria = "safe-to-deploy"

[[exemptions.unicode-ident]]
version = "1.0.4"
criteria = "safe-to-deploy"

[[exemptions.unicode-segmentation]]
version = "1.10.0"
criteria = "safe-to-deploy"

[[exemptions.unicode-width]]
version = "0.1.10"
criteria = "safe-to-deploy"

[[exemptions.vec_map]]
version = "0.8.2"
criteria = "safe-to-deploy"

[[exemptions.version_check]]
version = "0.9.4"
criteria = "safe-to-deploy"

[[exemptions.wasi]]
version = "0.11.0+wasi-snapshot-preview1"
criteria = "safe-to-deploy"

[[exemptions.winapi]]
version = "0.3.9"
criteria = "safe-to-deploy"

[[exemptions.winapi-i686-pc-windows-gnu]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.winapi-x86_64-pc-windows-gnu]]
version = "0.4.0"
criteria = "safe-to-deploy"

