/*
    Constants
*/

/*
    Directories for example files
*/
pub const EX_TOPDIR: &str = "examples";
// **Auto-generated** examples only
pub const EX_DIR_GENERATED: &str = "examples/generated";
// Handwritten
pub const EX_DIR_HANDWRITTEN: &str = "examples/handwritten";
// Regex examples -- generated by external script
// TODO: Integrate
// pub const EX_DIR_REGEX: &str = "examples/regex";

/*
    Output directory used by run_all
*/

pub const RESULTS_DIR: &str = "results";

/*
    List of ALL example test cases
    Each is a pair of (directory, prefix)

    The list of known examples is unfortunately maintained in several places:
    there is the actual folder examples/ containing everything, a list in
    example_gen of which are generated automatically by that binary, a
    partial list in test_examples of only those examples used as unit tests,
    and finally a list here of everything.
*/
pub const ALL_EXAMPLES: &[(&str, &str)] = &[
    (EX_DIR_HANDWRITTEN, "1"),
    (EX_DIR_HANDWRITTEN, "2"),
    (EX_DIR_HANDWRITTEN, "3"),
    (EX_DIR_HANDWRITTEN, "tree_3"),
    (EX_DIR_GENERATED, "line_3"),
    (EX_DIR_GENERATED, "line_10"),
    (EX_DIR_GENERATED, "line_20"),
    (EX_DIR_GENERATED, "line_100"),
    (EX_DIR_GENERATED, "line_1000"),
    (EX_DIR_GENERATED, "line_10000"),
    (EX_DIR_GENERATED, "liveline_3"),
    (EX_DIR_GENERATED, "liveline_10"),
    (EX_DIR_GENERATED, "liveline_20"),
    (EX_DIR_GENERATED, "liveline_100"),
    (EX_DIR_GENERATED, "liveline_1000"),
    (EX_DIR_GENERATED, "liveline_10000"),
    (EX_DIR_GENERATED, "liveloop_3"),
    (EX_DIR_GENERATED, "liveloop_10"),
    (EX_DIR_GENERATED, "liveloop_20"),
    (EX_DIR_GENERATED, "liveloop_100"),
    (EX_DIR_GENERATED, "liveloop_1000"),
    (EX_DIR_GENERATED, "liveloop_10000"),
    (EX_DIR_GENERATED, "loop_3"),
    (EX_DIR_GENERATED, "loop_10"),
    (EX_DIR_GENERATED, "loop_20"),
    (EX_DIR_GENERATED, "loop_100"),
    (EX_DIR_GENERATED, "loop_1000"),
    (EX_DIR_GENERATED, "loop_10000"),
    (EX_DIR_GENERATED, "reverseline_3"),
    (EX_DIR_GENERATED, "reverseline_10"),
    (EX_DIR_GENERATED, "reverseline_20"),
    (EX_DIR_GENERATED, "reverseline_100"),
    (EX_DIR_GENERATED, "reverseline_1000"),
    (EX_DIR_GENERATED, "reverseline_10000"),
    (EX_DIR_GENERATED, "reverseliveline_3"),
    (EX_DIR_GENERATED, "reverseliveline_10"),
    (EX_DIR_GENERATED, "reverseliveline_20"),
    (EX_DIR_GENERATED, "reverseliveline_100"),
    (EX_DIR_GENERATED, "reverseliveline_1000"),
    (EX_DIR_GENERATED, "reverseliveline_10000"),
    (EX_DIR_GENERATED, "reverseliveloop_3"),
    (EX_DIR_GENERATED, "reverseliveloop_10"),
    (EX_DIR_GENERATED, "reverseliveloop_20"),
    (EX_DIR_GENERATED, "reverseliveloop_100"),
    (EX_DIR_GENERATED, "reverseliveloop_1000"),
    (EX_DIR_GENERATED, "reverseliveloop_10000"),
    (EX_DIR_GENERATED, "reverseloop_3"),
    (EX_DIR_GENERATED, "reverseloop_10"),
    (EX_DIR_GENERATED, "reverseloop_20"),
    (EX_DIR_GENERATED, "reverseloop_100"),
    (EX_DIR_GENERATED, "reverseloop_1000"),
    (EX_DIR_GENERATED, "reverseloop_10000"),
];
