/*
    Constants
*/

/*
    File extensions
*/
pub const EXAMPLE_IN_EXT: &str = "_in.json";
pub const EXAMPLE_EXPECT_EXT: &str = "_expect.json";

/*
    Directories for example files
*/
pub const EX_TOPDIR: &str = "examples";
// **Auto-generated** examples only
pub const EX_DIR_GENERATED: &str = "examples/generated";
// Handwritten
pub const EX_DIR_HANDWRITTEN: &str = "examples/handwritten";
// Regex examples -- generated by external script
// (Having these as constants isn't really necessary, they are only
// used in the list below in this file.)
const EX_DIR_REGEX_COMP: &str = "examples/regex/complement";
const EX_DIR_REGEX_LOOP: &str = "examples/regex/loop";
const EX_DIR_REGEX_DATE: &str = "examples/regex/date";
const EX_DIR_REGEX_SGEASY: &str = "examples/regex/state_graph_easy";
const EX_DIR_REGEX_SGHARD: &str = "examples/regex/state_graph_hard";

/*
    Output directory used by run_all
*/

pub const RESULTS_DIR: &str = "results";

/*
    List of ALL example test cases
    Each is a pair of (directory, prefix)

    The list of known examples is unfortunately maintained in several places:
    there is the actual folder examples/ containing everything, a list in
    example_gen of which are generated automatically by that binary, a
    partial list in test_examples of only those examples used as unit tests,
    and finally a list here of everything.
*/
pub const ALL_EXAMPLES: &[(&str, &str)] = &[
    (EX_DIR_HANDWRITTEN, "1"),
    (EX_DIR_HANDWRITTEN, "2"),
    (EX_DIR_HANDWRITTEN, "3"),
    (EX_DIR_HANDWRITTEN, "4"),
    (EX_DIR_HANDWRITTEN, "5"),
    (EX_DIR_HANDWRITTEN, "6"),
    (EX_DIR_HANDWRITTEN, "7"),
    (EX_DIR_HANDWRITTEN, "8"),
    (EX_DIR_HANDWRITTEN, "9"),
    (EX_DIR_HANDWRITTEN, "10"),
    (EX_DIR_HANDWRITTEN, "11"),
    (EX_DIR_HANDWRITTEN, "12"),
    (EX_DIR_HANDWRITTEN, "13"),
    (EX_DIR_HANDWRITTEN, "14"),
    (EX_DIR_HANDWRITTEN, "15"),
    (EX_DIR_HANDWRITTEN, "tree_3"),
    (EX_DIR_GENERATED, "line_3"),
    (EX_DIR_GENERATED, "line_10"),
    (EX_DIR_GENERATED, "line_20"),
    (EX_DIR_GENERATED, "line_100"),
    (EX_DIR_GENERATED, "line_1000"),
    (EX_DIR_GENERATED, "line_10000"),
    (EX_DIR_GENERATED, "unkline_3"),
    (EX_DIR_GENERATED, "unkline_10"),
    (EX_DIR_GENERATED, "unkline_20"),
    (EX_DIR_GENERATED, "unkline_100"),
    (EX_DIR_GENERATED, "unkline_1000"),
    (EX_DIR_GENERATED, "unkline_10000"),
    (EX_DIR_GENERATED, "unkloop_3"),
    (EX_DIR_GENERATED, "unkloop_10"),
    (EX_DIR_GENERATED, "unkloop_20"),
    (EX_DIR_GENERATED, "unkloop_100"),
    (EX_DIR_GENERATED, "unkloop_1000"),
    (EX_DIR_GENERATED, "unkloop_10000"),
    (EX_DIR_GENERATED, "loop_3"),
    (EX_DIR_GENERATED, "loop_10"),
    (EX_DIR_GENERATED, "loop_20"),
    (EX_DIR_GENERATED, "loop_100"),
    (EX_DIR_GENERATED, "loop_1000"),
    (EX_DIR_GENERATED, "loop_10000"),
    (EX_DIR_GENERATED, "reverseline_3"),
    (EX_DIR_GENERATED, "reverseline_10"),
    (EX_DIR_GENERATED, "reverseline_20"),
    (EX_DIR_GENERATED, "reverseline_100"),
    (EX_DIR_GENERATED, "reverseline_1000"),
    (EX_DIR_GENERATED, "reverseline_10000"),
    (EX_DIR_GENERATED, "reverseunkline_3"),
    (EX_DIR_GENERATED, "reverseunkline_10"),
    (EX_DIR_GENERATED, "reverseunkline_20"),
    (EX_DIR_GENERATED, "reverseunkline_100"),
    (EX_DIR_GENERATED, "reverseunkline_1000"),
    (EX_DIR_GENERATED, "reverseunkline_10000"),
    (EX_DIR_GENERATED, "reverseunkloop_3"),
    (EX_DIR_GENERATED, "reverseunkloop_10"),
    (EX_DIR_GENERATED, "reverseunkloop_20"),
    (EX_DIR_GENERATED, "reverseunkloop_100"),
    (EX_DIR_GENERATED, "reverseunkloop_1000"),
    (EX_DIR_GENERATED, "reverseunkloop_10000"),
    (EX_DIR_GENERATED, "reverseloop_3"),
    (EX_DIR_GENERATED, "reverseloop_10"),
    (EX_DIR_GENERATED, "reverseloop_20"),
    (EX_DIR_GENERATED, "reverseloop_100"),
    (EX_DIR_GENERATED, "reverseloop_1000"),
    (EX_DIR_GENERATED, "reverseloop_10000"),
    (EX_DIR_REGEX_COMP, "comp1_inclusion_unsat"),
    (EX_DIR_REGEX_COMP, "comp1_nonempty_trivial_sat"),
    (EX_DIR_REGEX_COMP, "comp2_inclusion_sat"),
    (EX_DIR_REGEX_COMP, "simple_complement_unsat"),
    (EX_DIR_REGEX_DATE, "date_minimal_sat"),
    (EX_DIR_REGEX_DATE, "date_minimal_unsat"),
    (EX_DIR_REGEX_DATE, "date_unsat"),
    (EX_DIR_REGEX_DATE, "date1_sat"),
    (EX_DIR_REGEX_DATE, "date2_sat"),
    (EX_DIR_REGEX_LOOP, "deadloop1_sat"),
    (EX_DIR_REGEX_LOOP, "deadloop2_sat"),
    (EX_DIR_REGEX_LOOP, "deadloop3_unsat"),
    (EX_DIR_REGEX_LOOP, "evil1_unsat"),
    (EX_DIR_REGEX_LOOP, "evil2_inter_unsat"),
    (EX_DIR_REGEX_LOOP, "evil2_sat"),
    (EX_DIR_REGEX_LOOP, "nestedloop1_unsat"),
    (EX_DIR_REGEX_LOOP, "nestedloop2_sat"),
    (EX_DIR_REGEX_LOOP, "nestedloop2_unsat"),
    (EX_DIR_REGEX_SGEASY, "diamond_chain_10"),
    (EX_DIR_REGEX_SGEASY, "diamond_chain_30"),
    (EX_DIR_REGEX_SGEASY, "diamond_chain_100"),
    (EX_DIR_REGEX_SGEASY, "inter_1_2_3"),
    (EX_DIR_REGEX_SGEASY, "inter_3_6_9"),
    (EX_DIR_REGEX_SGEASY, "inter_star_3_3"),
    (EX_DIR_REGEX_SGEASY, "inter_star_10_10"),
    (EX_DIR_REGEX_SGEASY, "inter_star_30_30"),
    (EX_DIR_REGEX_SGEASY, "long_3"),
    (EX_DIR_REGEX_SGEASY, "long_10"),
    (EX_DIR_REGEX_SGHARD, "diamond_chain_300"),
    (EX_DIR_REGEX_SGHARD, "diamond_chain_1000"),
    (EX_DIR_REGEX_SGHARD, "diamond_chain_3000"),
    (EX_DIR_REGEX_SGHARD, "inter_10_20_30"),
    (EX_DIR_REGEX_SGHARD, "inter_30_60_90"),
    (EX_DIR_REGEX_SGHARD, "inter_star_100_100"),
    (EX_DIR_REGEX_SGHARD, "long_30"),
    (EX_DIR_REGEX_SGHARD, "long_100"),
    (EX_DIR_REGEX_SGHARD, "long_300"),
];
